/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbank3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Gurmanjit
 */
public class donationsection extends javax.swing.JFrame {

    /**
     * Creates new form donationsection
     */
    public donationsection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        opos = new javax.swing.JRadioButton();
        oneg = new javax.swing.JRadioButton();
        abneg = new javax.swing.JRadioButton();
        abpos = new javax.swing.JRadioButton();
        bpos = new javax.swing.JRadioButton();
        bneg = new javax.swing.JRadioButton();
        aneg = new javax.swing.JRadioButton();
        apos = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opos.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(opos);
        opos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opos.setForeground(new java.awt.Color(255, 255, 255));
        opos.setText("O+");
        opos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oposActionPerformed(evt);
            }
        });
        getContentPane().add(opos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 50, -1));

        oneg.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(oneg);
        oneg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oneg.setForeground(new java.awt.Color(255, 255, 255));
        oneg.setText("O-");
        oneg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onegActionPerformed(evt);
            }
        });
        getContentPane().add(oneg, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 50, -1));

        abneg.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(abneg);
        abneg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        abneg.setForeground(new java.awt.Color(255, 255, 255));
        abneg.setText("AB-");
        getContentPane().add(abneg, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 60, -1));

        abpos.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(abpos);
        abpos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        abpos.setForeground(new java.awt.Color(255, 255, 255));
        abpos.setText("AB+");
        getContentPane().add(abpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 60, -1));

        bpos.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(bpos);
        bpos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bpos.setForeground(new java.awt.Color(255, 255, 255));
        bpos.setText("B+");
        bpos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bposActionPerformed(evt);
            }
        });
        getContentPane().add(bpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 50, -1));

        bneg.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(bneg);
        bneg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bneg.setForeground(new java.awt.Color(255, 255, 255));
        bneg.setText("B-");
        getContentPane().add(bneg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 50, -1));

        aneg.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(aneg);
        aneg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aneg.setForeground(new java.awt.Color(255, 255, 255));
        aneg.setText("A-");
        aneg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anegActionPerformed(evt);
            }
        });
        getContentPane().add(aneg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 50, -1));

        apos.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(apos);
        apos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        apos.setForeground(new java.awt.Color(255, 255, 255));
        apos.setSelected(true);
        apos.setText("A+");
        apos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aposActionPerformed(evt);
            }
        });
        getContentPane().add(apos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 50, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELECT YOUR BLOODGROUP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 50, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PHONE NO.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 90, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADDRESS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 100, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STATE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 80, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("AGE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 40, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EMAIL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 70, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DATE   (YYYY-MM-DD)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 150, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 210, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 210, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 210, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 210, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 210, -1));

        jTextField7.setText("\n");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 210, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", "" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 210, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DONATE");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 120, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("BACK");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 120, 40));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank3/WELCOME TO DONATION SECTION (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oposActionPerformed

    private void onegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onegActionPerformed

    private void bposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bposActionPerformed

    private void anegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anegActionPerformed

    private void aposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aposActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
         String name,phone ,address, email , date,state,bloodgp;
         int age;
        name=jTextField1.getText();
        phone=jTextField2.getText();
        address=jTextField3.getText();
       age=Integer.parseInt(jTextField5.getText());
       if(age<16){
           JOptionPane.showMessageDialog(null,"YOUR AGE IS LESS TAHN 16 SO YOU ARE NOT ELIGIBLE TO DONATE");
           return;}
       email=jTextField6.getText();
       date=jTextField7.getText();
       if(apos.isSelected()==true){
       bloodgp=apos.getText();
       }
       else if(aneg.isSelected()==true){
       bloodgp=aneg.getText();
       }
       else if(bpos.isSelected()==true){
       bloodgp=bpos.getText();
       }
       else if(bneg.isSelected()==true){
       bloodgp=bneg.getText();
       }
       else if(abpos.isSelected()==true){
       bloodgp=abpos.getText();
       }
       else if(abneg.isSelected()==true){
       bloodgp=abneg.getText();
       }
       else if(opos.isSelected()==true){
       bloodgp=opos.getText();
       }
       else if(oneg.isSelected()==true){
       bloodgp=oneg.getText();
       }
       else{
       bloodgp="null";
       }
           int index=jComboBox1.getSelectedIndex();
           state=jComboBox1.getItemAt(index);

       try {
           
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3307/"
                    + "bloodbank", "root", "gurman");//Establishing connection
          System.out.println("Connected With the database successfully"); //Message after successful connection
             
         PreparedStatement preparedStatement =connection.prepareStatement("insert into "
                 + "infoblood values(?,?,?,?,?,?,?,?)");
         
               preparedStatement.setString(1,name);
               preparedStatement.setString(2,phone);
              preparedStatement.setString(3,address);
              preparedStatement.setString(4,state);
              preparedStatement.setInt(5,age);
              preparedStatement.setString(6,email);
              preparedStatement.setString(7,date);
              preparedStatement.setString(8,bloodgp);
              
         System.out.println("DRIVER LOADED SUCCESSFULLY");
        preparedStatement.executeUpdate();
        JOptionPane.showMessageDialog(null,"Your record has been saved successfully."
                + " Thank you for donating blood");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            apos.setSelected(true);
            jComboBox1.setSelectedIndex(-1);
            
            }
       catch(SQLException e) {
            System.out.println("DRIVER FAILED TO LOAD ");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        user user=new user();
        user.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(donationsection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(donationsection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(donationsection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(donationsection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new donationsection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton abneg;
    private javax.swing.JRadioButton abpos;
    private javax.swing.JRadioButton aneg;
    private javax.swing.JRadioButton apos;
    private javax.swing.JRadioButton bneg;
    private javax.swing.JRadioButton bpos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JRadioButton oneg;
    private javax.swing.JRadioButton opos;
    // End of variables declaration//GEN-END:variables
}
