/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbank3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gurmanjit
 */
public class recievingsection extends javax.swing.JFrame {

    /**
     * Creates new form recievingsection
     */
    public recievingsection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        apos = new javax.swing.JRadioButton();
        aneg = new javax.swing.JRadioButton();
        bpos = new javax.swing.JRadioButton();
        bneg = new javax.swing.JRadioButton();
        abneg = new javax.swing.JRadioButton();
        abpos = new javax.swing.JRadioButton();
        opos = new javax.swing.JRadioButton();
        oneg = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("SELECT THE BLOOD GROUP YOU NEED");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 290, -1));

        buttonGroup1.add(apos);
        apos.setText("A+");
        getContentPane().add(apos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        buttonGroup1.add(aneg);
        aneg.setText("A-");
        getContentPane().add(aneg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 37, -1));

        buttonGroup1.add(bpos);
        bpos.setText("B+");
        getContentPane().add(bpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 39, -1));

        buttonGroup1.add(bneg);
        bneg.setText("B-");
        getContentPane().add(bneg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 40, -1));

        buttonGroup1.add(abneg);
        abneg.setText("AB-");
        getContentPane().add(abneg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 50, -1));

        buttonGroup1.add(abpos);
        abpos.setText("AB+");
        getContentPane().add(abpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 45, -1));

        buttonGroup1.add(opos);
        opos.setText("O+");
        getContentPane().add(opos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 41, -1));

        buttonGroup1.add(oneg);
        oneg.setText("O-");
        getContentPane().add(oneg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 40, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", " PHONE NO.", "ADDRESS", "EMAIL", "STATE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 510, 230));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 120, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 120, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("BACK");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 80, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank3/world blood donation day.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        user us=new user();
        us.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String bloodgp;
         if(apos.isSelected()==true){
       bloodgp=apos.getText();
       }
       else if(aneg.isSelected()==true){
       bloodgp=aneg.getText();
       }
       else if(bpos.isSelected()==true){
       bloodgp=bpos.getText();
       }
       else if(bneg.isSelected()==true){
       bloodgp=bneg.getText();
       }
       else if(abpos.isSelected()==true){
       bloodgp=abpos.getText();
       }
       else if(abneg.isSelected()==true){
       bloodgp=abneg.getText();
       }
       else if(opos.isSelected()==true){
       bloodgp=opos.getText();
       }
       else if(oneg.isSelected()==true){
       bloodgp=oneg.getText();
       }
       else{
       bloodgp="null";
       }
        
           
          DefaultTableModel tm=(DefaultTableModel) jTable1.getModel();
           try{
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3307/"
                        + "bloodbank", "root", "gurman");//Establishing connection
                System.out.println("Connected With the database successfully"); //Message after successful connection

              System.out.println("DRIVER LOADED SUCCESSFULLYyyyyyyyy");
             
      
            
      PreparedStatement preparedStatement =connection.prepareStatement
        ("select name, phone_no,address,state,email from infoblood where  bloodType=?");
     
      preparedStatement.setString(1,bloodgp);
      
       
        ResultSet resultSet=preparedStatement.executeQuery();

        while(resultSet.next()){
                             String name=resultSet.getString("name");
                             String phone=resultSet.getString("phone_no");
                             String address=resultSet.getString("address");
                             String email=resultSet.getString("email");
                             String state=resultSet.getString("state");
                              Object rec[]={name,phone,address,email,state};
                             tm.addRow(rec);
           }
           }
           catch(SQLException e) {
            System.out.println("DRIVER FAILED TO LOAD ");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tm=(DefaultTableModel) jTable1.getModel();
        tm.setRowCount(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recievingsection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recievingsection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recievingsection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recievingsection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recievingsection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton abneg;
    private javax.swing.JRadioButton abpos;
    private javax.swing.JRadioButton aneg;
    private javax.swing.JRadioButton apos;
    private javax.swing.JRadioButton bneg;
    private javax.swing.JRadioButton bpos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton oneg;
    private javax.swing.JRadioButton opos;
    // End of variables declaration//GEN-END:variables
}
