/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbank3;

/**
 *
 * @author Gurmanjit
 */
public class welcome2 extends javax.swing.JFrame {

    /**
     * Creates new form welcome2
     */
    public welcome2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbuser = new javax.swing.JRadioButton();
        rbadmin = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbuser.setBackground(new java.awt.Color(232, 213, 195));
        buttonGroup1.add(rbuser);
        rbuser.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        rbuser.setSelected(true);
        rbuser.setText("USER");
        rbuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbuserActionPerformed(evt);
            }
        });
        getContentPane().add(rbuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 77, -1));

        rbadmin.setBackground(new java.awt.Color(232, 213, 195));
        buttonGroup1.add(rbadmin);
        rbadmin.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbadmin.setText("ADMIN");
        rbadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbadminActionPerformed(evt);
            }
        });
        getContentPane().add(rbadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 88, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("     NEXT");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 392, 110, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("      BACK");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank3/YOU ARE.........png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 509));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbuserActionPerformed
        // TODO add your handling code here:
        rbuser.setSelected(true);
    }//GEN-LAST:event_rbuserActionPerformed

    private void rbadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbadminActionPerformed
        // TODO add your handling code here:
        //        admin admin=new admin();
        //        if (rbadmin.isSelected()==true);
        //        admin.setVisible(true);
        //        setVisible(false);
    }//GEN-LAST:event_rbadminActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        user user=new user();
        welcome1 wc1=new welcome1();
        if (rbuser.isSelected()==true){
        //welcome wc= new welcome();
        user.setVisible(true);
        //wc1.setVisible(false);
        setVisible(false);
        }
         admin admin=new admin();
        if (rbadmin.isSelected()==true){
        admin.setVisible(true);
        setVisible(false);}
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        welcome1 wc1=new welcome1();
        wc1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbadmin;
    private javax.swing.JRadioButton rbuser;
    // End of variables declaration//GEN-END:variables
}
